### ISSUE TITLE
Publish package on hex.pm

### ISSUE THREAD

**Issue by obahareth** [sbacarob/vantagex#12]
It would be quite helpful if this package was published to [hex.pm](https://hex.pm) to be able to pin it to specific versions and so on.

**Comment by sbacarob** [comment]
Done!

Thanks again.

You can now use the dependency by including `{:vantagex, "~> 0.1"}` in your `deps`.

Links to the docs and the package url in hex.pm have been added to the README

**Comment by obahareth** [comment]
You are awesome!
